include: package:flutter_lints/flutter.yaml

analyzer:
  ###---------------------------------------
  exclude:
    - bricks/**
    - lib/core/util/localization/**

  ###---------------------------------------
  errors:
    avoid_print: warning
    empty_catches: warning
    always_specify_types: info
    always_use_package_imports: info
    annotate_overrides: info
    prefer_single_quotes: info
    require_trailing_commas: info
    directives_ordering: info
    parameter_assignments: info
    prefer_is_not_empty: info
    prefer_is_empty: info
    prefer_function_declarations_over_variables: info
    camel_case_extensions: info
    camel_case_types: info
    constant_identifier_names: info
    sort_child_properties_last: info
    unnecessary_final: info
    #    lines_longer_than_80_chars: warning
    #    prefer_final_parameters: warning

###---------------------------------------
linter:
  rules:
    - avoid_print
    - always_specify_types
    - empty_catches
    - always_use_package_imports
    - annotate_overrides
    - prefer_single_quotes
    - require_trailing_commas
    - directives_ordering
    - parameter_assignments
    - avoid_multiple_declarations_per_line
    - prefer_is_not_empty
    - prefer_is_empty
    - prefer_function_declarations_over_variables
    - camel_case_extensions
    - camel_case_types
    - constant_identifier_names
    - sort_child_properties_last
    - unnecessary_final
#    - lines_longer_than_80_chars
#    - prefer_final_parameters