name: process
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_image: ^4.1.11
  flutter_bloc: ^8.1.6
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  firebase_database: ^11.0.3
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_messaging: ^15.0.3
  gif_view: ^0.4.4
  firebase_app_check: ^0.3.0+3
  equatable: ^2.0.5
  intl_phone_field: ^3.2.0
  play_integrity_flutter: ^0.0.1
  flutter_launcher_icons: ^0.13.1
  transitioned_indexed_stack: ^1.0.2
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  translator: ^1.0.0
  mobile_scanner: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/logolast.png"
  adaptive_icon_background: "#ffffff"



flutter:

  uses-material-design: true

  assets:
  - assets/
  - assets/image/
  - assets/image/fill/
  - assets/image/taste/
  - assets/image/color/
  - assets/image/cakes/
  - assets/image/main_screen/
  - assets/image/main_screen/pies/
  - assets/image/topping/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - weight: 800
        - asset: assets/fonts/OpenSans-Bold.ttf
        - weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - weight: 600
        - asset: assets/fonts/OpenSans-Medium.ttf
        - weight: 500
        - asset: assets/fonts/OpenSans-Light.ttf
        - weight: 300