name: process
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_image: ^4.1.11
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  firebase_database: ^11.0.3
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_messaging: ^15.0.4
  gif_view: ^0.4.4
  firebase_app_check: ^0.3.0+3
  equatable: ^2.0.5
  intl_phone_field: ^3.2.0
  transitioned_indexed_stack: ^1.0.2
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  translator: ^1.0.0
  shared_preferences: ^2.3.2
  animations: ^2.0.11
  shimmer: ^3.0.0
  flutter_3d_controller: ^1.3.1
  webview_flutter: ^4.8.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  mask_text_input_formatter: ^2.9.0
  introduction_screen: ^3.1.14

  #  flutter_launcher_icons: ^0.13.1
  #  mobile_scanner: ^5.2.1
  #  flutter_bloc: ^8.1.6
  #  hydrated_bloc: ^9.1.5
  #  path_provider: ^2.0.0
  #  connectivity_plus: ^6.0.5

  flutter_bloc: ^8.0.0
  hydrated_bloc: ^8.0.0
  path_provider: ^2.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  connectivity_plus:

#  flutter_launcher_icons: ^0.13.1

# flutter_launcher_icons:
#   android: true
#   image_path: "assets/logo.png"
#   adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/fonts/inter/
    - assets/image/
    - assets/image/fill/
    - assets/image/taste/
    - assets/image/color/
    - assets/image/main_screen/
      #  - assets/models/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
          weight: 800